version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "80:80"
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - datavolume:/var/db/

volumes:
  datavolume:
    
